server:
  port: 8087

spring:
  application:
    name: manager
  data:
    mongodb:
      uri: "mongodb+srv://admin:1234@mariaenriqueta.f47y4yu.mongodb.net/vg-ms-mariaenriqueta?retryWrites=true&w=majority"